"""
Script:      build_index.py
Description: Generates scripts/README.md from the header block of every script
             in scripts/, so the index of what each one does is derived rather
             than maintained.

             A hand-written index is a second place the same facts live, and it
             disagrees with reality the first time someone edits a script and
             forgets it. The same reasoning produced check_facts.py, which
             re-derives every stated number, and fetch_sources.py, which
             replaced a README code block that nothing executed.

             The second purpose matters more than the index. CLAUDE.md requires
             a header block on every script, and until now nothing enforced it,
             so it held only while everyone remembered. This fails on a script
             whose header is missing or incomplete, which turns that rule into
             a checked one.

             Only the Script, Description and Usage fields reach the generated
             page, and only the first paragraph of Description. The index is a
             directory pointing at the scripts, not a copy of them; the full
             header stays the single place to read the detail.

Inputs:      scripts/*.py   (read-only, parsed rather than imported)

Outputs:     scripts/README.md, overwritten in full on every run.
             Writes nothing under --check.

Usage:       python scripts/build_index.py
                 regenerate scripts/README.md
             python scripts/build_index.py --check
                 report whether the file on disk is current; write nothing.
                 For hooks and CI.
             python scripts/build_index.py --quiet
                 print nothing; use the exit code

Exit codes:  0  the index was written, or --check found it current
             1  --check found scripts/README.md stale or missing
             2  a script has no header block, or is missing a required field
             3  no scripts found, or one could not be parsed as Python

             2 outranks 1, because an index generated from an incomplete header
             would be wrong rather than merely out of date.

Date:        2026-08-24
Owner:       Jason Delosh
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

# Resolved from this file's own location rather than the working directory, so
# the script behaves the same run from the repo root or from inside scripts/.
# Same approach as verify_manifests.py.
REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
INDEX_PATH = SCRIPTS_DIR / "README.md"


### Constants ##################################################################

# Every field CLAUDE.md requires. Presence is checked for all of them, though
# only Description and Usage are printed. Checking the full set is the point: a
# script that documents what it does but not what it writes still fails.
REQUIRED_FIELDS = (
    "Script",
    "Description",
    "Inputs",
    "Outputs",
    "Usage",
    "Exit codes",
    "Date",
    "Owner",
)

# A field starts at column 0 with a capitalised label and a colon. Continuation
# lines are indented, which is what separates a real field from a colon
# appearing inside prose.
FIELD_RE = re.compile(r"^([A-Z][A-Za-z ]*):[ \t]*(.*)$")

# Written into the generated file so nobody edits it by hand and loses the edit
# on the next run.
GENERATED_NOTICE = (
    "Generated by `python scripts/build_index.py`. Do not edit by hand: "
    "change the header block of the script itself and regenerate."
)


### Header parsing #############################################################


def parse_header(path: Path) -> tuple[dict[str, list[str]] | None, str | None]:
    """
    Read one script's header block. Returns (fields, error), exactly one of which is None.

    The file is parsed with ast rather than imported, so reading a script never
    runs it. That matters because these scripts touch the network and the
    filesystem, and building an index must not.

    Field values are kept as lists of raw lines with their leading whitespace
    stripped of the common indent, because Usage relies on relative indentation
    to show which explanation belongs to which invocation.
    """
    # A file that will not parse is reported rather than raised, so that one bad
    # script does not hide the state of the rest.
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError) as exc:
        return None, f"cannot parse ({exc})"

    docstring = ast.get_docstring(tree, clean=False)

    if not docstring:
        return None, "no module docstring, so no header block"

    fields: dict[str, list[str]] = {}
    current: str | None = None

    for line in docstring.splitlines():
        match = FIELD_RE.match(line)

        if match:
            current = match.group(1)
            fields[current] = [match.group(2)]
            continue

        # Anything else belongs to the field above it. Lines before the first
        # field are dropped; there are none in this repo's convention, but a
        # stray line should not become a phantom field.
        if current is not None:
            fields[current].append(line)

    return fields, None


def dedent_value(lines: list[str]) -> list[str]:
    """
    Strip the common leading indent from a field's continuation lines.

    The header aligns continuations under the value column, so every line after
    the first carries the same wide indent. Removing exactly that much preserves
    the extra indentation that Usage uses to attach an explanation to the
    invocation above it.
    """
    # The first line already has its indent consumed by the field label, so it
    # is excluded when measuring.
    continuations = [line for line in lines[1:] if line.strip()]

    if not continuations:
        return [lines[0].rstrip()]

    common = min(len(line) - len(line.lstrip()) for line in continuations)

    dedented = [lines[0].rstrip()] + [line[common:].rstrip() for line in lines[1:]]

    # Trailing blanks come from the blank line separating this field from the
    # next one in the source header. They would render as an empty line inside
    # the generated code block.
    while dedented and not dedented[-1]:
        dedented.pop()

    return dedented


def first_paragraph(lines: list[str]) -> str:
    """
    Return a field's first paragraph as one unwrapped line.

    Descriptions are hard-wrapped in the source header and run to several
    paragraphs. The index wants the opening one only, joined back into a single
    line because this repo's markdown is one paragraph per line so that grep
    can match a phrase.
    """
    paragraph: list[str] = []

    for line in lines:
        if not line.strip():
            # A blank line ends the first paragraph, but only once something has
            # been collected, so a header that starts with a blank line is fine.
            if paragraph:
                break
            continue

        paragraph.append(line.strip())

    return " ".join(paragraph)


### Rendering ##################################################################


def render(entries: list[tuple[str, dict[str, list[str]]]]) -> str:
    """
    Build the whole of scripts/README.md from the parsed headers.

    Returns the text rather than writing it, so that --check can compare against
    the file on disk without a temporary file.
    """
    out = [
        "# scripts/",
        "",
        GENERATED_NOTICE,
        "",
        "Everything here is run by hand. Importable pipeline code lives in `src/sdg/`.",
        "",
        "Each entry is a summary. The script's own header block is the full account of "
        "its inputs, outputs and exit codes.",
        "",
    ]

    for name, fields in entries:
        out.append(f"## {name}")
        out.append("")
        out.append(first_paragraph(dedent_value(fields["Description"])))
        out.append("")
        out.append("```")
        out.extend(line for line in dedent_value(fields["Usage"]))
        out.append("```")
        out.append("")

    # Exactly one trailing newline, so a regenerated file compares equal to
    # itself and --check does not fail on whitespace.
    return "\n".join(out).rstrip("\n") + "\n"


### Entry point ################################################################


def main() -> int:
    """
    Parse every script's header, then write or check the index.

    Returns the process exit code. Header problems are collected across all
    scripts before returning, so one run names every script that needs fixing
    rather than stopping at the first.
    """
    parser = argparse.ArgumentParser(
        description="Generate scripts/README.md from each script's header block."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report whether the index is current; write nothing",
    )
    parser.add_argument("--quiet", action="store_true", help="print nothing; use the exit code")
    args = parser.parse_args()

    def say(message: str = "") -> None:
        if not args.quiet:
            print(message)

    paths = sorted(p for p in SCRIPTS_DIR.glob("*.py") if p.name != "__init__.py")

    if not paths:
        say("no scripts found")
        return 3

    entries: list[tuple[str, dict[str, list[str]]]] = []
    unparseable: list[str] = []
    incomplete: list[str] = []

    for path in paths:
        fields, error = parse_header(path)

        if error:
            # "cannot parse" is a broken file; a missing docstring is a broken
            # header. Separated because they need different fixes and different
            # exit codes.
            (unparseable if "cannot parse" in error else incomplete).append(
                f"{path.name}: {error}"
            )
            continue

        missing = [field for field in REQUIRED_FIELDS if field not in fields]

        if missing:
            incomplete.append(f"{path.name}: header missing {', '.join(missing)}")
            continue

        entries.append((path.name, fields))

    for problem in unparseable + incomplete:
        say(problem)

    if unparseable:
        return 3

    if incomplete:
        say()
        say("CLAUDE.md requires the full header block on every script. Index not written.")
        return 2

    generated = render(entries)

    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else None

        if current == generated:
            say(f"scripts/README.md is current, {len(entries)} script(s)")
            return 0

        say("scripts/README.md is stale. Run: python scripts/build_index.py")
        return 1

    INDEX_PATH.write_text(generated, encoding="utf-8")
    say(f"scripts/README.md written, {len(entries)} script(s)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
